<a href="https://colab.research.google.com/github/Yaffa16/tf-Keras/blob/master/NN_on_CSV_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How to run a ML model on CSV data file


*  We take in a CSV data file
*  We try to predict one of the columns of the data by training the model on the other columns 
* We first import the data as a pandas data format 
* Then we convert the data into a numpy format to feed the keras/tensorflow
* we create a model
* we fit the model 
* Find the RMSE 
* See what the predictions look like

In [7]:

import tensorflow as tf
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 1.15.0

### Simple Tensorflow Regression

Read the CSV file

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])


cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())
df[0:10]

    mpg  cylinders  displacement  ...  year  origin                       name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino
5  15.0          8         429.0  ...    70       1           ford galaxie 500
6  14.0          8         454.0  ...    70       1           chevrolet impala
7  14.0          8         440.0  ...    70       1          plymouth fury iii
8  14.0          8         455.0  ...    70       1           pontiac catalina
9  15.0          8         390.0  ...    70       1         amc ambassador dpl

[10 rows x 9 columns]

Accesss the values for the columns that we need to train on and put it in x 
Put the y prediction values in y

In [0]:
# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

Create the model

In [0]:
# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')

Fit the model

In [17]:
model.fit(x,y,verbose=2,epochs=100)

Train on 398 samples
Epoch 1/100
398/398 - 0s - loss: 17739.0752
Epoch 2/100
398/398 - 0s - loss: 2686.9393
Epoch 3/100
398/398 - 0s - loss: 414.2082
Epoch 4/100
398/398 - 0s - loss: 255.1235
Epoch 5/100
398/398 - 0s - loss: 190.0621
Epoch 6/100
398/398 - 0s - loss: 154.6818
Epoch 7/100
398/398 - 0s - loss: 140.7930
Epoch 8/100
398/398 - 0s - loss: 138.6439
Epoch 9/100
398/398 - 0s - loss: 134.9979
Epoch 10/100
398/398 - 0s - loss: 131.8687
Epoch 11/100
398/398 - 0s - loss: 129.7921
Epoch 12/100
398/398 - 0s - loss: 127.4648
Epoch 13/100
398/398 - 0s - loss: 125.4138
Epoch 14/100
398/398 - 0s - loss: 121.7046
Epoch 15/100
398/398 - 0s - loss: 121.5456
Epoch 16/100
398/398 - 0s - loss: 117.7422
Epoch 17/100
398/398 - 0s - loss: 115.2680
Epoch 18/100
398/398 - 0s - loss: 113.0709
Epoch 19/100
398/398 - 0s - loss: 110.2243
Epoch 20/100
398/398 - 0s - loss: 106.8698
Epoch 21/100
398/398 - 0s - loss: 104.9034
Epoch 22/100
398/398 - 0s - loss: 103.0433
Epoch 23/100
398/398 - 0s - loss: 100.2282
Epoch 24/100
398/398 - 0s - loss: 96.9646
Epoch 25/100
398/398 - 0s - loss: 95.3204
Epoch 26/100
398/398 - 0s - loss: 93.4785
Epoch 27/100
398/398 - 0s - loss: 90.2038
Epoch 28/100
398/398 - 0s - loss: 88.3458
Epoch 29/100
398/398 - 0s - loss: 86.3621
Epoch 30/100
398/398 - 0s - loss: 85.1090
Epoch 31/100
398/398 - 0s - loss: 82.7175
Epoch 32/100
398/398 - 0s - loss: 79.7788
Epoch 33/100
398/398 - 0s - loss: 78.4656
Epoch 34/100
398/398 - 0s - loss: 76.0334
Epoch 35/100
398/398 - 0s - loss: 74.8683
Epoch 36/100
398/398 - 0s - loss: 77.4661
Epoch 37/100
398/398 - 0s - loss: 74.0342
Epoch 38/100
398/398 - 0s - loss: 73.2653
Epoch 39/100
398/398 - 0s - loss: 71.4674
Epoch 40/100
398/398 - 0s - loss: 68.6278
Epoch 41/100
398/398 - 0s - loss: 68.4228
Epoch 42/100
398/398 - 0s - loss: 63.9773
Epoch 43/100
398/398 - 0s - loss: 62.2166
Epoch 44/100
398/398 - 0s - loss: 60.9199
Epoch 45/100
398/398 - 0s - loss: 59.7794
Epoch 46/100
398/398 - 0s - loss: 58.7020
Epoch 47/100
398/398 - 0s - loss: 57.8093
Epoch 48/100
398/398 - 0s - loss: 57.3184
Epoch 49/100
398/398 - 0s - loss: 55.1707
Epoch 50/100
398/398 - 0s - loss: 54.0059
Epoch 51/100
398/398 - 0s - loss: 54.5505
Epoch 52/100
398/398 - 0s - loss: 52.4475
Epoch 53/100
398/398 - 0s - loss: 51.6687
Epoch 54/100
398/398 - 0s - loss: 51.1557
Epoch 55/100
398/398 - 0s - loss: 52.7233
Epoch 56/100
398/398 - 0s - loss: 56.4669
Epoch 57/100
398/398 - 0s - loss: 49.9747
Epoch 58/100
398/398 - 0s - loss: 48.2082
Epoch 59/100
398/398 - 0s - loss: 48.6335
Epoch 60/100
398/398 - 0s - loss: 48.5849
Epoch 61/100
398/398 - 0s - loss: 47.5540
Epoch 62/100
398/398 - 0s - loss: 45.8582
Epoch 63/100
398/398 - 0s - loss: 46.6181
Epoch 64/100
398/398 - 0s - loss: 45.6151
Epoch 65/100
398/398 - 0s - loss: 44.3634
Epoch 66/100
398/398 - 0s - loss: 44.1291
Epoch 67/100
398/398 - 0s - loss: 43.9312
Epoch 68/100
398/398 - 0s - loss: 43.4018
Epoch 69/100
398/398 - 0s - loss: 43.1275
Epoch 70/100
398/398 - 0s - loss: 41.7026
Epoch 71/100
398/398 - 0s - loss: 40.9756
Epoch 72/100
398/398 - 0s - loss: 41.3815
Epoch 73/100
398/398 - 0s - loss: 40.4340
Epoch 74/100
398/398 - 0s - loss: 41.3312
Epoch 75/100
398/398 - 0s - loss: 38.7789
Epoch 76/100
398/398 - 0s - loss: 37.6287
Epoch 77/100
398/398 - 0s - loss: 37.7283
Epoch 78/100
398/398 - 0s - loss: 38.6264
Epoch 79/100
398/398 - 0s - loss: 36.5936
Epoch 80/100
398/398 - 0s - loss: 37.0023
Epoch 81/100
398/398 - 0s - loss: 36.6450
Epoch 82/100
398/398 - 0s - loss: 38.0046
Epoch 83/100
398/398 - 0s - loss: 38.1821
Epoch 84/100
398/398 - 0s - loss: 35.3493
Epoch 85/100
398/398 - 0s - loss: 34.4690
Epoch 86/100
398/398 - 0s - loss: 35.9271
Epoch 87/100
398/398 - 0s - loss: 36.2289
Epoch 88/100
398/398 - 0s - loss: 33.9660
Epoch 89/100
398/398 - 0s - loss: 35.9212
Epoch 90/100
398/398 - 0s - loss: 34.0582
Epoch 91/100
398/398 - 0s - loss: 34.2796
Epoch 92/100
398/398 - 0s - loss: 34.7712
Epoch 93/100
398/398 - 0s - loss: 35.2865
Epoch 94/100
398/398 - 0s - loss: 33.2022
Epoch 95/100
398/398 - 0s - loss: 32.4403
Epoch 96/100
398/398 - 0s - loss: 33.3466
Epoch 97/100
398/398 - 0s - loss: 31.8924
Epoch 98/100
398/398 - 0s - loss: 31.1400
Epoch 99/100
398/398 - 0s - loss: 31.8032
Epoch 100/100
398/398 - 0s - loss: 32.1606

Predict the  values

In [18]:
pred = model.predict(x)
print("Shape: {}".format(pred.shape))
print(pred)

Shape: (398, 1)
[[11.327271 ]
 [10.593313 ]
 [11.58159  ]
 [13.307111 ]
 [12.318388 ]
 [ 7.2563095]
 [ 6.477012 ]
 [ 7.2673926]
 [ 7.32076  ]
 [ 8.593682 ]
 [ 6.6643047]
 [10.17171  ]
 [ 3.529708 ]
 [ 2.2664118]
 [26.822721 ]
 [18.369377 ]
 [18.229248 ]
 [16.364805 ]
 [26.88504  ]
 [22.588385 ]
 [27.675879 ]
 [26.76244  ]
 [27.978926 ]
 [26.287975 ]
 [16.979095 ]
 [18.292143 ]
 [21.953812 ]
 [21.424875 ]
 [23.672417 ]
 [27.13059  ]
 [22.623676 ]
 [26.319353 ]
 [27.450096 ]
 [14.110828 ]
 [18.908407 ]
 [15.278483 ]
 [14.024624 ]
 [17.092863 ]
 [12.889316 ]
 [ 9.238956 ]
 [11.728431 ]
 [14.729085 ]
 [13.432146 ]
 [ 9.92629  ]
 [11.893391 ]
 [13.566991 ]
 [22.158165 ]
 [14.998235 ]
 [13.204046 ]
 [23.734747 ]
 [24.761896 ]
 [27.83426  ]
 [26.364962 ]
 [27.319277 ]
 [26.767124 ]
 [23.874557 ]
 [25.924677 ]
 [27.061592 ]
 [26.345716 ]
 [26.075708 ]
 [24.234064 ]
 [24.5163   ]
 [13.380158 ]
 [ 9.289049 ]
 [15.224424 ]
 [11.776847 ]
 [14.597554 ]
 [10.014871 ]
 [13.588806 ]
 [13.895122 ]
 [10.971192 ]
 [31.88892  ]
 [15.6334715]
 [14.471089 ]
 [17.128359 ]
 [15.108182 ]
 [29.732264 ]
 [25.402588 ]
 [28.642456 ]
 [26.25011  ]
 [25.051527 ]
 [28.869717 ]
 [27.14307  ]
 [26.02387  ]
 [27.673532 ]
 [14.1341095]
 [14.843032 ]
 [10.831819 ]
 [15.826846 ]
 [13.913233 ]
 [10.6073   ]
 [ 7.4329953]
 [13.385619 ]
 [16.060226 ]
 [10.1140175]
 [10.248171 ]
 [11.576305 ]
 [18.404428 ]
 [16.090141 ]
 [16.391712 ]
 [13.660311 ]
 [19.476553 ]
 [23.8638   ]
 [ 9.855651 ]
 [10.835858 ]
 [14.65141  ]
 [16.017286 ]
 [15.597595 ]
 [29.108015 ]
 [22.725424 ]
 [28.344688 ]
 [30.684944 ]
 [25.393568 ]
 [23.291176 ]
 [28.066076 ]
 [11.1864605]
 [13.89661  ]
 [26.701607 ]
 [24.253212 ]
 [27.300337 ]
 [29.93779  ]
 [12.178339 ]
 [28.652664 ]
 [26.489302 ]
 [12.557521 ]
 [20.572086 ]
 [19.455141 ]
 [16.471197 ]
 [16.349356 ]
 [28.050299 ]
 [25.280735 ]
 [28.701157 ]
 [23.277811 ]
 [18.02909  ]
 [17.756659 ]
 [20.507109 ]
 [16.631292 ]
 [14.549013 ]
 [16.93089  ]
 [18.917778 ]
 [18.118345 ]
 [27.671436 ]
 [27.032543 ]
 [27.196026 ]
 [25.233835 ]
 [27.236418 ]
 [26.660286 ]
 [27.15442  ]
 [24.522947 ]
 [27.672588 ]
 [28.334206 ]
 [27.280035 ]
 [18.372698 ]
 [17.33383  ]
 [15.091012 ]
 [13.748768 ]
 [10.511178 ]
 [13.234157 ]
 [17.536495 ]
 [14.129103 ]
 [22.610003 ]
 [19.500343 ]
 [18.577394 ]
 [20.955414 ]
 [18.101496 ]
 [14.79779  ]
 [11.741278 ]
 [27.327564 ]
 [24.65733  ]
 [16.765812 ]
 [24.308073 ]
 [26.786608 ]
 [27.655428 ]
 [28.649553 ]
 [23.10727  ]
 [25.947714 ]
 [17.132286 ]
 [28.693884 ]
 [28.878563 ]
 [29.170454 ]
 [29.5625   ]
 [24.703087 ]
 [28.1853   ]
 [26.087223 ]
 [25.082651 ]
 [27.80783  ]
 [27.52363  ]
 [16.868084 ]
 [16.311403 ]
 [14.2875595]
 [12.94652  ]
 [18.857975 ]
 [16.871157 ]
 [19.386759 ]
 [17.02549  ]
 [26.717846 ]
 [26.544144 ]
 [26.230139 ]
 [24.923595 ]
 [20.908113 ]
 [16.448492 ]
 [18.80229  ]
 [15.109779 ]
 [24.710012 ]
 [27.909348 ]
 [27.594889 ]
 [22.869461 ]
 [29.835392 ]
 [15.408875 ]
 [31.31178  ]
 [26.757074 ]
 [29.849072 ]
 [16.222578 ]
 [11.61581  ]
 [15.344773 ]
 [14.874788 ]
 [27.054874 ]
 [25.754192 ]
 [26.983711 ]
 [26.777668 ]
 [27.933561 ]
 [16.226215 ]
 [19.803852 ]
 [16.032    ]
 [17.174051 ]
 [18.616983 ]
 [19.959776 ]
 [21.074274 ]
 [18.017952 ]
 [10.189026 ]
 [14.552941 ]
 [11.770973 ]
 [13.706104 ]
 [26.553396 ]
 [24.600788 ]
 [28.625107 ]
 [25.91569  ]
 [25.590595 ]
 [27.38824  ]
 [26.400259 ]
 [27.435188 ]
 [26.401266 ]
 [29.161825 ]
 [34.742496 ]
 [26.270973 ]
 [24.607124 ]
 [27.888475 ]
 [29.033884 ]
 [25.898329 ]
 [16.707336 ]
 [14.166197 ]
 [15.115692 ]
 [21.092829 ]
 [21.884514 ]
 [19.714714 ]
 [25.850988 ]
 [20.462244 ]
 [17.906101 ]
 [19.80951  ]
 [20.295782 ]
 [22.447325 ]
 [18.265165 ]
 [14.898189 ]
 [25.321188 ]
 [13.409206 ]
 [15.571106 ]
 [26.619207 ]
 [27.034904 ]
 [27.989002 ]
 [26.397705 ]
 [26.988173 ]
 [26.093666 ]
 [25.320946 ]
 [28.426456 ]
 [29.000534 ]
 [28.163595 ]
 [31.218733 ]
 [30.402443 ]
 [27.27035  ]
 [27.255491 ]
 [20.423277 ]
 [20.54738  ]
 [27.128408 ]
 [18.564686 ]
 [21.28014  ]
 [15.722101 ]
 [15.109604 ]
 [11.44006  ]
 [14.700947 ]
 [15.05894  ]
 [12.423606 ]
 [18.430115 ]
 [11.509549 ]
 [27.07227  ]
 [27.60832  ]
 [26.655376 ]
 [27.136318 ]
 [24.56645  ]
 [10.956581 ]
 [28.412664 ]
 [16.616556 ]
 [25.782167 ]
 [25.937735 ]
 [28.718576 ]
 [27.603235 ]
 [25.019588 ]
 [23.472855 ]
 [24.19775  ]
 [24.014345 ]
 [27.810595 ]
 [27.750566 ]
 [26.953163 ]
 [28.268648 ]
 [25.39797  ]
 [27.462671 ]
 [27.364088 ]
 [20.11639  ]
 [28.512789 ]
 [27.882828 ]
 [27.747446 ]
 [28.56753  ]
 [27.538889 ]
 [28.933159 ]
 [26.320072 ]
 [29.310999 ]
 [27.175333 ]
 [28.348873 ]
 [28.404339 ]
 [27.33779  ]
 [26.718678 ]
 [30.264364 ]
 [28.07818  ]
 [26.396168 ]
 [27.812637 ]
 [34.27546  ]
 [27.772123 ]
 [27.342451 ]
 [27.82626  ]
 [25.943975 ]
 [24.884735 ]
 [24.638298 ]
 [24.241568 ]
 [24.972782 ]
 [27.671247 ]
 [27.157736 ]
 [27.500551 ]
 [27.96594  ]
 [29.06656  ]
 [28.196445 ]
 [28.037477 ]
 [25.994577 ]
 [26.560957 ]
 [28.77946  ]
 [27.166462 ]
 [30.416609 ]
 [27.5101   ]
 [28.43725  ]
 [30.223112 ]
 [28.412283 ]
 [29.015009 ]
 [27.473621 ]
 [26.730988 ]
 [29.88133  ]
 [21.158115 ]
 [ 9.195726 ]
 [21.364717 ]
 [19.767939 ]
 [30.324558 ]
 [30.251282 ]
 [29.203289 ]
 [29.225119 ]
 [26.383316 ]
 [26.41216  ]
 [27.969713 ]
 [28.393938 ]
 [26.81502  ]
 [28.88844  ]
 [28.550045 ]
 [25.843264 ]
 [27.826233 ]
 [27.41246  ]
 [27.75235  ]
 [27.8087   ]
 [27.89732  ]
 [28.041672 ]
 [28.26187  ]
 [25.222698 ]
 [14.349222 ]
 [24.772318 ]
 [19.071058 ]
 [27.353662 ]
 [25.18218  ]
 [27.080011 ]
 [26.946472 ]
 [28.061346 ]
 [24.611597 ]
 [28.45563  ]
 [29.37584  ]]

In [19]:
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 5.625576834426618

In [24]:
# Sample predictions
for i in range(10):
    print(f"{i+1}. Index: {cars[i]}, mpg: {y[i]}, predicted mpg: {pred[i]}")

1. Index: chevrolet chevelle malibu, mpg: 18.0, predicted mpg: [11.327271]
2. Index: buick skylark 320, mpg: 15.0, predicted mpg: [10.593313]
3. Index: plymouth satellite, mpg: 18.0, predicted mpg: [11.58159]
4. Index: amc rebel sst, mpg: 16.0, predicted mpg: [13.307111]
5. Index: ford torino, mpg: 17.0, predicted mpg: [12.318388]
6. Index: ford galaxie 500, mpg: 15.0, predicted mpg: [7.2563095]
7. Index: chevrolet impala, mpg: 14.0, predicted mpg: [6.477012]
8. Index: plymouth fury iii, mpg: 14.0, predicted mpg: [7.2673926]
9. Index: pontiac catalina, mpg: 14.0, predicted mpg: [7.32076]
10. Index: amc ambassador dpl, mpg: 15.0, predicted mpg: [8.593682]